In [2]:
import numpy as np
a = np.array([7])
b = np.array([[4,6,8],[3,5,7]])
c = np.array([3,3,3])
d = np.array([[3,2,1],[1,2,3]])
e = np.array([5,10])

In [7]:
display(a*b)

array([[28, 42, 56],
       [21, 35, 49]])

In [8]:
display(d-b)

array([[-1, -4, -7],
       [-2, -3, -4]])

In [5]:
display(c+b)

array([[ 7,  9, 11],
       [ 6,  8, 10]])

In [9]:
display(c+e)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 