In [6]:
import numpy as np

In [5]:
#Crie 2 arrays a e b com as seguintes listas a.[[4,6,8],[3,5,7]] b. [[11,13,17],[23,29,31]]
a = np.array([[4,6,8],[3,5,7]])
b = np.array([[11,13,17],[23,29,31]])

In [7]:
#Use a função cbrt() e calcule a raiz cúbica dos arrays a e b
np.cbrt(a)

In [8]:
np.cbrt(b)

array([[2.22398009, 2.35133469, 2.57128159],
       [2.84386698, 3.07231683, 3.14138065]])

In [9]:
#Calcule a soma cumulativa de a
a.cumsum()

array([ 4, 10, 18, 21, 26, 33], dtype=int32)

In [10]:
#Calcule a média de a e b
display(a.mean())
display(b.mean())

5.5

20.666666666666668

In [12]:
#Aplique a função np.negative() no array b e soma com b. O que aconteceu?
neg_b = np.negative(b)
neg_b + b

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
#Concatenar
a = np.array([1,2])
b = np.array([3,4,5,6])
c = np.array([7,8,9])
display(np.concatenate([a,b,c]))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2