In [6]:
import numpy as np
#Crie 2 arrays com as seguintes listas
#a. [[1,2,3],[4,5,6]]
#b. [[2,4,6,8],10,12,14,16]
#c. [[11,13,17],[[23,29,31]]
#d. [[13,14,5],[19,21,23]]
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6,8],[10,12,14,16]])
c = np.array([[11,13,17],[23,29,31]])
d = np.array([[13,14,5],[19,21,23]])

In [3]:
#Concatene a e b. O que aconteceu?
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions

In [8]:
#Concatene b e c, tanto usando o eixo 0 (linha) quanto o eixo 1 (coluna)
np.concatenate((a,c))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 13, 17],
       [23, 29, 31]])

In [10]:
#Concatene a e d, tanto usando o eixo 0 (linha) quanto o eixo 1 (coluna)
np.concatenate((a,d), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14,  5],
       [19, 21, 23]])

In [11]:
np.concatenate((a,d), axis = 1)

array([[ 1,  2,  3, 13, 14,  5],
       [ 4,  5,  6, 19, 21, 23]])