In [1]:
import numpy as np

In [21]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
display(data.ndim)
display(data.size)
display(data.shape)

1

16

(16,)

In [26]:
data2 = data.reshape(4,4)
display(data2.ndim)
display(data2.size)
display(data2.shape)
data2

2

16

(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
data_t = data2.transpose()
data_t

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [30]:
data_flat = data_t.flatten()
data_flat

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [29]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
(data==data_flat).sum()

4