In [9]:
import numpy as np

In [3]:
#Arrays

In [10]:
np.array([1,2,3])

array([1, 2, 3])

In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
one = np.ones([2,2])
one

array([[1., 1.],
       [1., 1.]])

In [17]:
zeros = np.zeros([2,2,2])
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
data = np.array([0,1,9,3,4,5,6,7,8,9])

In [21]:
data[2]

9

In [22]:
data[2:4]

array([9, 3])

In [26]:
vet = np.array([[1,2,3],[4,5,6],[7,8,9]])
vet

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
vet[1,:]

array([4, 5, 6])

In [19]:
vet[:,2]

In [20]:
vet[1,1]

In [38]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [39]:
arr.shape

(2, 2, 2)

In [42]:
arr[0,1,1]

4

In [41]:
arr[1,1,0]

7

In [45]:
data = np.arange(10)
data[0:5]

array([0, 1, 2, 3, 4])

In [53]:
data#[0:5] = -99

array([ -99,  -99, 5555, 5555,  -99,    5,    6,    7,    8,    9])

In [54]:
data_1 = data[0:5]# apontando para o endereço de data
data_1

array([ -99,  -99, 5555, 5555,  -99])

In [56]:
data#_1[2:4] = 5555

array([ -99,  -99, 5555, 5555,  -99,    5,    6,    7,    8,    9])

In [63]:
data_c = data[5:].copy()
data_1[0:4] = 999
data

array([999, 999, 999, 999, -99,   5,   6,   7,   8,   9])

In [69]:
data = np.array([10,32,45,4,3,7,99,88])

In [71]:
data[data>=10]

array([10, 32, 45, 99, 88])

In [72]:
data[data == 4]

array([4])

In [73]:
data[data != 4]

array([10, 32, 45,  3,  7, 99, 88])

In [74]:
#Array: funções úteis
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
data2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]]) 
data3 = np.array([[1],[2],[3],[4],[5]])
data4 = np.array([1,2,3,4,5])

In [75]:
display(data1.shape)

(3, 3)

In [76]:
display(data2.shape)

(3, 4)

In [77]:
display(data3.shape)

(5, 1)

In [78]:
display(data4.shape)

(5,)

In [79]:
len(data1)

3

In [80]:
len(data2)

3

In [81]:
len(data3)

5

In [82]:
len(data4)

5

In [83]:
data1.ndim

2

In [84]:
data2.ndim

2

In [85]:
data3.ndim

2

In [86]:
data4.ndim

1

In [87]:
data1.size

9

In [88]:
data2.size

12

In [90]:
data3.size

5

In [91]:
data4.size

5

In [95]:
data2#.reshape(4,3)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [94]:
data2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [99]:
data3.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [101]:
data1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
data2.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [105]:
data3.flatten()

array([1, 2, 3, 4, 5])

In [107]:
data4.flatten()

array([1, 2, 3, 4, 5])

In [111]:
data1#.transpose()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
data1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [112]:
data2#.transpose()

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [113]:
data2.transpose()

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [114]:
a = np.array([[1,2],[3,4]])

In [115]:
a*2

array([[2, 4],
       [6, 8]])

In [116]:
a+3

array([[4, 5],
       [6, 7]])

In [117]:
a-2

array([[-1,  0],
       [ 1,  2]])

In [118]:
a/5

array([[0.2, 0.4],
       [0.6, 0.8]])

In [119]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [130]:
b = np.array([[1,2],[3,4]])

In [121]:
a+b

array([[2, 4],
       [6, 8]])

In [122]:
a-b

array([[0, 0],
       [0, 0]])

In [123]:
a>b

array([[False, False],
       [False, False]])

In [131]:
a==b

array([[ True,  True],
       [ True,  True]])

In [129]:
(a==b).sum()

3

In [132]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [133]:
np.sqrt(a)
#square root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [134]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [135]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [136]:
np.negative(a)

array([[-1, -2],
       [-3, -4]])

In [144]:
a = np.array([[15,22],[7,12]])

In [140]:
a.mean()

14.0

In [143]:
a.min()

2

In [145]:
a.max()

22

In [146]:
a.sum()

56

In [147]:
a.cumsum()

array([15, 37, 44, 56], dtype=int32)

In [151]:
#Concatenar
a = np.array([1,2])
b = np.array([3,4,5,6])
c = np.array([7,8,9])
d = np.concatenate((a,b,c))
d[d<7]

array([1, 2, 3, 4, 5, 6])

In [152]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [153]:
b = np.array([[5,6],[7,8]])
b

In [26]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [155]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [162]:
a = np.array([[[5,6],[7,8]],[[5,6],[7,8]]], float)
a

array([[[5., 6.],
        [7., 8.]],

       [[5., 6.],
        [7., 8.]]])

In [161]:
b = np.array([[[1,1],[3,4]],[[1,2],[3,4]]], float)
b

array([[[1., 1.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])

In [217]:
#c = np.concatenate((a,b), axis = 0)
#display(c[0,0,1])
#display(c[0][0][1])
c[0][0][1]

6.0

In [192]:
d = np.concatenate((a,b), axis = 1)