In [2]:
import numpy as np

In [3]:
#Arrays

In [3]:
np.array([1,2,3])

In [5]:
np.array([[1,2,3],[4,5,6]])

In [7]:
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [9]:
one = np.ones([2,2])

In [10]:
zeros = np.zeros([2,2,2])

In [11]:
data = np.array([0,1,2,3,4,5,6,7,8,9])

In [14]:
data[2]

2

In [13]:
data[2:4]

In [17]:
vet = np.array([[1,2,3],[4,5,6],[7,8,9]])
vet

In [18]:
vet[1,:]

In [19]:
vet[:,2]

In [20]:
vet[1,1]

In [22]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [23]:
arr.shape

In [24]:
arr[0,0,1]

In [27]:
arr[1,1,0]

In [31]:
data = np.arange(10)
data[0:5]

In [32]:
data[0:5] = -99

In [34]:
data_1 = data[0:5]
data_1

In [35]:
data_1[2:4] = 5555

In [37]:
data_c = data[5:].copy()

In [40]:
data = np.arange(10)

In [41]:
data[data>5]

In [42]:
data[data == 4]

In [43]:
data[data != 4]

In [80]:
#Array: funções úteis
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
data2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]]) 
data3 = np.array([[1],[2],[3],[4],[5]])
data4 = np.array([1,2,3,4,5])

In [52]:
display(data1.shape)

(3, 3)

In [53]:
display(data2.shape)

(3, 4)

In [54]:
display(data3.shape)

(5, 1)

In [51]:
display(data4.shape)

In [59]:
len(data1)

3

In [56]:
len(data2)

3

In [57]:
len(data3)

5

In [58]:
len(data4)

In [63]:
data1.ndim

2

In [62]:
data2.ndim

2

In [64]:
data3.ndim

2

In [65]:
data4.ndim

In [69]:
data1.size

9

In [68]:
data2.size

12

In [67]:
data3.size

5

In [66]:
data4.size

In [71]:
data2.reshape(4,3)

In [73]:
data3.reshape(1,5)

In [79]:
data1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
data2.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [77]:
data3.flatten()

array([1, 2, 3, 4, 5])

In [76]:
data4.flatten()

In [84]:
data1.transpose()

In [85]:
data2.transpose()

In [86]:
a = np.array([[1,2],[3,4]])

In [87]:
a*2

In [88]:
a+3

In [89]:
a-2

In [90]:
a/5

In [91]:
a**2

In [92]:
b = np.array([[1,2],[3,4]])

In [93]:
a+b

In [94]:
a-b

In [95]:
a>b

In [96]:
a==b

In [99]:
a*b

In [100]:
np.sqrt(a)

In [101]:
np.exp(a)

In [102]:
np.sin(a)

In [103]:
np.negative(a)

In [110]:
a = np.array([[15,22],[7,12]])

In [105]:
a.mean()

In [106]:
a.min()

In [107]:
a.max()

In [108]:
a.sum()

In [111]:
a.cumsum()

In [18]:
#Concatenar
a = np.array([1,2])
b = np.array([3,4,5,6])
c = np.array([7,8,9])
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [21]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [26]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
np.concatenate((a,b), axis = 1)

In [40]:
a = np.array([[[5,6],[7,8]],[[5,6],[7,8]]], float)
a

array([[[5., 6.],
        [7., 8.]],

       [[5., 6.],
        [7., 8.]]])

In [41]:
b = np.array([[[1,1],[3,4]],[[1,2],[3,4]]], float)
b

array([[[1., 1.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])

In [46]:
np.concatenate((a,b), axis = 0)

array([[[5., 6.],
        [7., 8.]],

       [[5., 6.],
        [7., 8.]],

       [[1., 1.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]]])

In [44]:
np.concatenate((a,b), axis = 1)

array([[[5., 6.],
        [7., 8.],
        [1., 1.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.],
        [1., 2.],
        [3., 4.]]])